import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
            fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"]
      },
      colors: {
        "on-tertiary": "#ffffff",
        secondary: "#4d616c",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#364954",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3f4",
        "tertiary-fixed-dim": "#84d5c8",
        "on-primary-container": "#a2e1ff",
        "surface-dim": "#dadadb",
        "on-surface": "#1a1c1d",
        surface: "#faf9fa",
        "on-surface-variant": "#3f484d",
        "primary-fixed-dim": "#87d0f2",
        "on-background": "#1a1c1d",
        background: "#faf9fa",
        "outline-variant": "#bfc8cd",
        "on-tertiary-container": "#95e7da",
        "surface-container": "#eeeeee",
        "secondary-container": "#d0e6f3",
        "inverse-surface": "#2f3131",
        "inverse-primary": "#87d0f2",
        error: "#ba1a1a",
        "surface-container-highest": "#e3e2e3",
        "surface-tint": "#016684",
        outline: "#70787e",
        "on-tertiary-fixed-variant": "#005048",
        "tertiary-container": "#006a60",
        "on-primary-fixed-variant": "#004d64",
        "surface-container-high": "#e8e8e9",
        "on-secondary-fixed": "#081e27",
        "primary-container": "#006684",
        "primary-fixed": "#bee9ff",
        "on-primary": "#ffffff",
        primary: "#004d64",
        "tertiary-fixed": "#9ff2e4",
        "secondary-fixed-dim": "#b4cad6",
        "surface-variant": "#e3e2e3",
        "inverse-on-surface": "#f1f0f1",
        "on-tertiary-fixed": "#00201c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d0e6f3",
        "surface-bright": "#faf9fa",
        "on-primary-fixed": "#001f2a",
        "on-secondary-container": "#536772",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        tertiary: "#005048",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          muted: "hsl(var(--sidebar-muted))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
