from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any, List
import json
import base64
from pathlib import Path
import uuid
from datetime import datetime

from src.agents.clinical_reader_agent import extract as clinical_extract
from src.agents.policy_agent import run_policy_agent
from src.agents.appeal_agent import generate_appeal
from src.core.form_filler import fill_pa_form

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

OUTPUT_DIR = Path("output")
DASHBOARD_METRICS_PATH = OUTPUT_DIR / "dashboard_metrics.json"
RUN_HISTORY_PATH = OUTPUT_DIR / "run_history.json"
POLICIES_DIR = Path("policies")
VECTOR_STORE_DIR = Path("vector_store")
SUPPORTED_PAYERS = ["aetna", "uhc", "cigna"]

def _now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def _load_metrics() -> dict:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not DASHBOARD_METRICS_PATH.is_file():
        return {"total_runs": 0, "approvals": 0, "denials": 0,
                "pending_more_info": 0, "errors": 0, "cumulative_days_saved": 0.0}
    try:
        return json.loads(DASHBOARD_METRICS_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {"total_runs": 0, "approvals": 0, "denials": 0,
                "pending_more_info": 0, "errors": 0, "cumulative_days_saved": 0.0}

def _save_metrics(m: dict) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DASHBOARD_METRICS_PATH.write_text(json.dumps(m, indent=2), encoding="utf-8")

def _load_history() -> List[Dict[str, Any]]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not RUN_HISTORY_PATH.is_file():
        return []
    try:
        data = json.loads(RUN_HISTORY_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except Exception:
        return []

def _append_history(record: Dict[str, Any]) -> None:
    history = _load_history()
    history.append(record)
    RUN_HISTORY_PATH.write_text(json.dumps(history, indent=2), encoding="utf-8")

def _estimate_days_saved(decision: str) -> float:
    if decision == "APPROVED":        return 3.0
    if decision == "DENIED":          return 1.0
    if decision == "PENDING_MORE_INFO": return 0.5
    return 0.0

def _generate_filled_form(clinical_bundle: Dict[str, Any], input_data: Any) -> Dict[str, Any]:
    patient_id_label = str(input_data) if isinstance(input_data, int) else "ehr"
    project_root = Path(__file__).resolve().parent
    template_pdf = project_root / "data" / "inputs" / "PA-Request-Form-UHC-Community-Plan.pdf"
    output_pdf = OUTPUT_DIR / f"patient_{patient_id_label}_filled_form.pdf"

    labs_evidence = clinical_bundle.get("supporting_evidence", "")
    if isinstance(labs_evidence, list):
        labs_evidence = "\n".join(str(e) for e in labs_evidence)

    mapped_data = {
        "name": clinical_bundle.get("patient_name", "John Doe"),
        "member_id": f"UHC-{uuid.uuid4().hex[:6].upper()}",
        "dob": "01/01/1990",
        "address": "N/A",
        "city": "N/A",
        "state": "N/A",
        "zip": "000000",
        "phone": "0000000000",
        "allergies": "NKA",
        "provider": "Dr. AutoAuth",
        "npi": "1234567890",
        "specialty": "General",
        "office_phone": "0000000000",
        "office_fax": "0000000000",
        "office_address": "AutoAuth Clinic",
        "office_city": "N/A",
        "office_state": "N/A",
        "office_zip": "000000",
        "medication": clinical_bundle.get("cpt_code", ""),
        "strength": "",
        "directions": "",
        "quantity": "",
        "diagnosis": clinical_bundle.get("summary", ""),
        "icd": ", ".join(clinical_bundle.get("icd_codes", [])),
        "history": clinical_bundle.get("summary", ""),
        "contra": "N/A",
        "labs": labs_evidence,
        "additional": "Auto-generated by AutoAuth Agent",
        "date": datetime.now().strftime("%m/%d/%Y"),
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    fill_pa_form(mapped_data, str(template_pdf), str(output_pdf))
    encoded_pdf = base64.b64encode(output_pdf.read_bytes()).decode("utf-8")
    return {
        "filled_form_path": str(output_pdf),
        "filled_form_base64": encoded_pdf,
        "filled_form_template_found": template_pdf.is_file(),
    }

def _build_appeals_data() -> Dict[str, Any]:
    history = _load_history()
    denied = [run for run in history if run.get("status") == "DENIED"]
    pending = [run for run in history if run.get("status") == "PENDING_MORE_INFO"]
    approvals = [run for run in history if run.get("status") == "APPROVED"]
    appeal_candidates = list(reversed(denied[-10:]))

    payer_breakdown: Dict[str, int] = {}
    for run in denied:
        payer_id = (run.get("payer_id") or "unknown").lower()
        payer_breakdown[payer_id] = payer_breakdown.get(payer_id, 0) + 1

    return {
        "summary": {
            "denied_count": len(denied),
            "appeal_candidates": len(appeal_candidates),
            "pending_more_info": len(pending),
            "recovered_cases": len(approvals),
            "top_denial_payer": max(payer_breakdown, key=payer_breakdown.get) if payer_breakdown else None,
        },
        "recent_denials": appeal_candidates,
        "payer_breakdown": payer_breakdown,
    }

def _build_policy_library_data() -> Dict[str, Any]:
    policies: List[Dict[str, Any]] = []
    total_policy_files = 0
    total_vector_files = 0

    for payer in SUPPORTED_PAYERS:
        payer_policy_dir = POLICIES_DIR / payer
        payer_vector_dir = VECTOR_STORE_DIR / payer
        policy_files = sorted([p for p in payer_policy_dir.glob("*") if p.is_file()]) if payer_policy_dir.exists() else []
        vector_files = sorted([p for p in payer_vector_dir.glob("*") if p.is_file()]) if payer_vector_dir.exists() else []
        total_policy_files += len(policy_files)
        total_vector_files += len(vector_files)

        if vector_files:
            status = "Indexed"
        elif policy_files:
            status = "Pending Ingestion"
        else:
            status = "No Policies"

        latest_file = None
        if policy_files or vector_files:
            latest_file = max(policy_files + vector_files, key=lambda p: p.stat().st_mtime)

        policies.append({
            "payer_id": payer,
            "payer_name": payer.upper() if payer == "uhc" else payer.title(),
            "policy_count": len(policy_files),
            "vector_file_count": len(vector_files),
            "status": status,
            "last_updated": datetime.fromtimestamp(latest_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S") if latest_file else None,
            "latest_assets": [p.name for p in (policy_files + vector_files)[-3:]],
        })

    health_status = "Operational" if total_vector_files > 0 else "Setup Required"
    alert = None if total_vector_files > 0 else "No vector indexes detected yet. Ingest payer policy documents to enable retrieval."

    return {
        "policies": policies,
        "store_health": {
            "status": health_status,
            "total_policy_files": total_policy_files,
            "total_vector_files": total_vector_files,
            "indexed_payers": len([p for p in policies if p["status"] == "Indexed"]),
            "alert": alert,
        },
    }

class RunPipelineRequest(BaseModel):
    input_mode: str = "EHR Note"
    ehr_note: str = ""
    csv_patient: int = 1
    payer: str = "aetna"
    force_denial: bool = False

@app.post("/api/run_pipeline")
def run_pipeline(req: RunPipelineRequest):
    input_data = req.ehr_note if req.input_mode == "EHR Note" else req.csv_patient
    
    # Optional logic for parsing demo payers
    payer = req.payer.lower()
    if payer in ["payer_a", "payer a", "payer_a (demo)"]:
        payer = "aetna"

    try:
        clinical_bundle = clinical_extract(input_data, payer=payer)
    except Exception as e:
        return {"error": str(e)}

    result = {
        "clinical_bundle": clinical_bundle,
        "pa_decision": None,
        "appeal_letter": None,
        "filled_form_path": None,
        "filled_form_base64": None,
        "pipeline_summary": {},
    }

    if "error" in clinical_bundle:
        result["pa_decision"] = {"decision": "ERROR", "reason": clinical_bundle.get("error"), "confidence": 0}
        result["pipeline_summary"] = {"status": "FAILED_AT_CLINICAL_READER", "payer": payer}
        return result

    try:
        pa_decision = run_policy_agent(clinical_bundle, vector_store_dir="./vector_store")
    except Exception as e:
        pa_decision = {"decision": "ERROR", "reason": f"Policy agent failed: {e}", "confidence": 0}

    if req.force_denial:
        forced = dict(pa_decision or {})
        forced["decision"] = "DENIED"
        forced.setdefault("confidence", 0)
        forced.setdefault("reason", "Forced denial for demo.")
        forced.setdefault("criteria_missing", ["Demo: missing documentation"])
        forced.setdefault("appeal_hint", "Provide documentation and re-submit.")
        pa_decision = forced

    result["pa_decision"] = pa_decision
    decision = (pa_decision or {}).get("decision", "ERROR")
    pre = (pa_decision or {}).get("pre_submission_risk") or {}

    if decision == "DENIED":
        try:
            patient_for_appeal = {
                "payer": clinical_bundle.get("payer", ""),
                "icd_codes": clinical_bundle.get("icd_codes", []),
                "cpt_code": clinical_bundle.get("cpt_code", ""),
                "summary": clinical_bundle.get("summary", ""),
                "evidence": clinical_bundle.get("supporting_evidence", []),
            }
            result["appeal_letter"] = generate_appeal(patient_for_appeal, pa_decision)
        except Exception as e:
            result["appeal_letter"] = f"Appeal generation failed: {e}"

    try:
        form_result = _generate_filled_form(clinical_bundle, input_data)
        result.update(form_result)
    except Exception as e:
        result["filled_form_error"] = str(e)

    result["pipeline_summary"] = {
        "status": decision,
        "payer": clinical_bundle.get("payer"),
        "icd_codes": clinical_bundle.get("icd_codes"),
        "cpt_code": clinical_bundle.get("cpt_code"),
        "all_codes": clinical_bundle.get("codes", {}),
        "confidence": (pa_decision or {}).get("confidence"),
        "pre_approval_score": pre.get("approval_probability"),
        "risk_level": pre.get("risk_level"),
        "extraction_method": clinical_bundle.get("extraction_method"),
        "policy_sources": (pa_decision or {}).get("policy_sources", []),
    }

    # Save Metrics & History
    metrics = _load_metrics()
    metrics["total_runs"] = int(metrics.get("total_runs", 0)) + 1
    if decision == "APPROVED":         
        metrics["approvals"] = int(metrics.get("approvals",0)) + 1
    elif decision == "DENIED":         
        metrics["denials"] = int(metrics.get("denials",0)) + 1
    elif decision == "PENDING_MORE_INFO": 
        metrics["pending_more_info"] = int(metrics.get("pending_more_info",0)) + 1
    else:                              
        metrics["errors"] = int(metrics.get("errors",0)) + 1
        
    metrics["cumulative_days_saved"] = float(metrics.get("cumulative_days_saved",0.0)) + _estimate_days_saved(decision)
    _save_metrics(metrics)
    
    _append_history({
        "ts": _now_ts(), "payer_id": payer,
        "cpt_codes": [clinical_bundle.get("cpt_code") or ""],
        "icd_codes": clinical_bundle.get("icd_codes") or [],
        "status": decision,
        "confidence": (pa_decision or {}).get("confidence"),
    })

    return result

@app.get("/api/dashboard_data")
def get_dashboard_data():
    metrics = _load_metrics()
    history = _load_history()
    return {"metrics": metrics, "history": history}

@app.get("/api/appeals_data")
def get_appeals_data():
    return _build_appeals_data()

@app.get("/api/policy_library_data")
def get_policy_library_data():
    return _build_policy_library_data()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="127.0.0.1", port=8000, reload=True)
